name: Generate Anonymous Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          for dir in $(find . -name 'package.json' -exec dirname {} \;); do
            cd "$dir"
            npm install
            cd - # Volta para o diretório anterior
          done

      - name: Generate token
        run: |
          jwt=$(npm run generate:token | tail -n 1 | sed 's/Bearer //')
          message="Remember to add the token to the Auth header"
          echo -e "Anonymous JWT token is:\n$jwt\n$message"
        working-directory: valida_cpf_usuario

