name: Generate Anonymous Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          for dir in $(find . -name 'package.json' -exec dirname {} \;); do
            cd "$dir"
            npm install
            cd - # Volta para o diretório anterior
          done

      - name: Generate token
        run: |
          jwt=$(npm run generate:token | tail -n 1)
          echo "jwt=$jwt" >> $GITHUB_ENV
        working-directory: valida_cpf_usuario

      - name: Get value
        run: echo -e "Anonymous JWT token is:\n${{ env.jwt }}"
